### ISSUE TITLE
requestParams is not a function

### ISSUE THREAD

**Issue by manhhungpm** [MrFatMeow/vn-paygate#1]
https://github.com/MrFatMeow/vn-paygate/blame/f8ad332caa5945f6fc3dd5aa4aded95814faec22/src/onepay/core.ts#L70C5-L70C5

**Comment by MrFatMeow** [comment]
Thanks mr.@manhhungpm for your helpful feedback!
I just updated the 1.0.2 version for this issue. 
Check it out at https://www.npmjs.com/package/vn-paymentgate
Hope it help!
